# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer 1
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: orderer1.tradeenergy.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - localhost
  # ---------------------------------------------------------------------------
  # Orderer 2
  # New orderer. Add also in compose-test-net.yaml a new container for it
  # ---------------------------------------------------------------------------
  - Name: Orderer2
    Domain: orderer2.tradeenergy.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer2
        SANS:
          - localhost
