# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer 1
  # ---------------------------------------------------------------------------
  - Name: Orderer1
    Domain: example.com
    EnableNodeOUs: true
     Specs:
      - Hostname: orderer1
        SANS:
          - localhost
  # ---------------------------------------------------------------------------
  # Orderer 2
  # ---------------------------------------------------------------------------
  - Name: Orderer2
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer2
        SANS:
          - localhost
