# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer 1
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: orderers.energytrade.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer1
        SANS:
          - localhost
         # TLS section
        #ServerTLSCert: organizations/ordererOrganizations/orderers.energytrade.com/orderers/orderer1.orderers.energytrade.com/tls/server.crt
        #ServerTLSKey: organizations/ordererOrganizations/orderers.energytrade.com/orderers/orderer1.orderers.energytrade.com/tls/server.key
        

  # ---------------------------------------------------------------------------
  # Orderer 2
  # New orderer. Add also in compose-test-net.yaml a new container for it ?
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: orderers.energytrade.com  #same organization, different orderer
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer2
        SANS:
          - localhost
  # ---------------------------------------------------------------------------
  # Orderer 3
  # New orderer. Add also in compose-test-net.yaml a new container for it ?
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: orderers.energytrade.com  #same organization, different orderer
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer3
        SANS:
          - localhost
